const $=id=>document.getElementById(id),jobsEl=$("jobs"),state=[];
const savedApi=localStorage.getItem("xanvora_worker_url")||window.XANVORA_VIDEO_API_URL||"",savedToken=localStorage.getItem("xanvora_worker_token")||"";
const workerInput=$("workerUrl"),tokenInput=$("workerToken"); if(workerInput) workerInput.value=savedApi;if(tokenInput) tokenInput.value=savedToken;
function api(){return (workerInput?.value.trim()||window.XANVORA_VIDEO_API_URL||"").replace(/\/$/,"")}function token(){return tokenInput?.value.trim()||""}
function headers(){return {"content-type":"application/json","X-Xanvora-Token":token()}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function render(){jobsEl.innerHTML=state.length?state.map(j=>'<div class="job"><b>'+esc(j.status)+' · '+esc(j.engine)+'</b><div class="meta">'+esc(j.prompt)+'<br>'+esc(j.id)+' · '+esc(j.duration)+'s</div>'+(j.video_url?'<p><a href="'+j.video_url+'" target="_blank" rel="noopener">Open video</a></p>':"")+(j.error?'<div class="meta">'+esc(j.error)+'</div>':"")+'</div>').join(""):'<div class="empty">No jobs yet.</div>'}
async function poll(job,base){if(!job.id)return;for(let i=0;i<720;i++){await new Promise(r=>setTimeout(r,3000));try{const r=await fetch(base+"/v1/video/jobs/"+encodeURIComponent(job.id),{headers:{"X-Xanvora-Token":token()}});if(!r.ok)continue;const data=await r.json();Object.assign(job,data);if(data.video_url&&!/^https?:\/\//.test(data.video_url))job.video_url=base+data.video_url;render();if(["completed","error"].includes(job.status))return}catch(e){}}}
$("generate").onclick=async()=>{const prompt=$("prompt").value.trim(),base=api(),tok=token();if(!prompt){$("notice").textContent="Enter a prompt first.";return}if(!base||!tok){$("notice").textContent="Paste the Colab Worker URL and Worker Token first.";return}
localStorage.setItem("xanvora_worker_url",base);localStorage.setItem("xanvora_worker_token",tok);const job={id:"local-"+Date.now(),prompt,engine:$("engine").value,duration:Number($("duration").value),status:"queued"};state.unshift(job);render();$("notice").textContent="Checking GPU worker…";
try{const h=await fetch(base+"/health",{headers:{"X-Xanvora-Token":tok}});if(!h.ok)throw new Error("Worker health check failed (HTTP "+h.status+")");const r=await fetch(base+"/v1/video/jobs",{method:"POST",headers:headers(),body:JSON.stringify({prompt,engine:job.engine,duration:job.duration})});if(!r.ok){const t=await r.text();throw new Error("HTTP "+r.status+" "+t)}Object.assign(job,await r.json());render();$("notice").textContent="Generation running on Colab GPU…";poll(job,base)}catch(e){job.status="error";render();$("notice").textContent="Worker request failed: "+e.message}};
render();