const q=s=>document.querySelector(s);
const file=q('#file'),empty=q('#empty'),picked=q('#picked'),preview=q('#preview'),results=q('#results');
const searchBtn=q('#search'),status=q('#search-status'),research=q('#research'),routes=q('#routes'),copyBtn=q('#copy-report');
let f=null,evidence={};
q('#choose').onclick=()=>file.click(); q('#drop').classList.add('dropzone'); file.onchange=e=>set(e.target.files[0]);
function set(x){if(!x||!x.type.startsWith('image/'))return;f=x;preview.src=URL.createObjectURL(x);q('#name').textContent=x.name;q('#size').textContent=(x.size/1024/1024).toFixed(2)+' MB';q('#filetype').textContent=x.type;q('#filesize').textContent=(x.size/1024/1024).toFixed(2)+' MB';empty.hidden=true;picked.hidden=false}
q('#clear').onclick=()=>location.reload();
q('#analyze').onclick=async()=>{if(!f)return;results.hidden=false;q('#hash').textContent='computing…';const buf=await f.arrayBuffer(),h=await crypto.subtle.digest('SHA-256',buf);const hash=[...new Uint8Array(h)].map(v=>v.toString(16).padStart(2,'0')).join('');const img=await createImageBitmap(f);evidence={name:f.name,type:f.type,size:f.size,width:img.width,height:img.height,sha256:hash};q('#hash').textContent=hash.slice(0,16)+'…';q('#step-fingerprint').textContent='complete';q('#step-search').textContent='browser ready';q('#step-context').textContent='local';searchBtn.disabled=false;copyBtn.disabled=false;results.scrollIntoView({behavior:'smooth'})};
searchBtn.onclick=()=>{if(!f)return;q('#step-search').textContent='prepared';q('#step-context').textContent='ready';status.textContent='No API was used. Choose a public search route below; the image stays in your browser unless you upload it yourself to a selected service.';research.hidden=false;routes.innerHTML='';const text=encodeURIComponent(evidence.name||'image');const items=[['Google Images','Search image-related web results','https://www.google.com/search?tbm=isch&q='+text],['Bing Images','Search visual/image results','https://www.bing.com/images/search?q='+text],['Google Lens','Open the public Lens entry point','https://lens.google.com/'],['TinEye','Open reverse-image search','https://tineye.com/']];for(const [name,desc,url] of items){const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.className='route';a.innerHTML='<strong>'+name+'</strong><span>'+desc+'</span>';routes.appendChild(a)}};
copyBtn.onclick=async()=>{const report=['XANVORA — LOCAL EVIDENCE','File: '+evidence.name,'Type: '+evidence.type,'Size: '+(evidence.size/1024/1024).toFixed(2)+' MB','Dimensions: '+evidence.width+' × '+evidence.height,'SHA-256: '+evidence.sha256,'Mode: API-free / browser-local analysis'].join('\n');await navigator.clipboard.writeText(report);status.textContent='Evidence summary copied to clipboard.'};